name: Build PS5 Payload

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang lld make wget unzip

    - name: Download and install PS5 Payload SDK
      run: |
        wget https://github.com/ps5-payload-dev/sdk/releases/latest/download/ps5-payload-sdk.zip
        unzip ps5-payload-sdk.zip -d ps5-payload-sdk

    - name: Build payload
      run: |
        cd power_control
        make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Control-Power-PS5-Bin
        path: power_control/*.bin
